### ISSUE TITLE
Prompt Engineering to increase the Accuracy for TestEvaluator

### ISSUE THREAD

**Issue by tonyshumlh** [UBC-MDS/test-creation#117]
Improve the accuracy for TestEvaluator to be more align with Human Evaluation on ML repo

**Comment by tonyshumlh** [comment]
Models:
1. Original setting as of 20240527
2. Prompt Engineering on the `Requirement` part of the 7 selected Checklist Item
3. Removing the `Title` from Checklist Object to be inserted into ChatGPT

Below are the 5 test runs result per Each Model:
<img width="934" alt="Screenshot 2024-05-29 at 3 14 49 PM" src="https://github.com/UBC-MDS/test-creation/assets/38127942/4e56de6c-e1f4-4628-bdd3-0d522382ab57">
<img width="679" alt="Screenshot 2024-05-29 at 3 15 02 PM" src="https://github.com/UBC-MDS/test-creation/assets/38127942/17001d96-1dff-4ce9-9faa-ebf54e6f7f72">

**Comment by JohnShiuMK** [comment]
@tonyshumlh 
Sorry for the late request. If time allowed, can you please:
 1. generate the 2nd table (sample variance) with 20 to 30 runs?
   - it would be the best if you could also generate the (un-adjusted) p-value for each trial, compared to the original
   - (otherwise, i could also easily calculate them)
 2. add the 4th trial: taking "Explanation" into account

**Comment by tonyshumlh** [comment]
> add the 4th trial: taking "Explanation" into account

Tried and it does not lead to improvement in accuracy and consistency with 5 test runs
