### ISSUE TITLE
Meeting Minutes for Week 3

### ISSUE THREAD

**Issue by SoloSynth1** [UBC-MDS/test-creation#51]
**Sprint Planning - 2024/05/13 Week 3**
- TODOs:
- [x] User Story 2: User can get ML test completion score #24
  - [x] #52
  - [x] #53
  - [x] #54
  - [x] #55
  - [x] #56
  - [x] #66
- [ ] User Story 3: Researcher/Leader get the checklist to push the best practice for ML test #25 
  - [ ] #57
- [x] Presentation with Mentor and/or Partner
  - [x] #58
  - [x] #59

**Comment by tonyshumlh** [comment]
Mentor Meeting - 2024/05/15 Week 3
- Agenda: 1) partner presentation on Friday; 2) API usage; 3) overview on how to move from checklist into application & pipeline
- Leader Update
    - Share the message of inviting collaboration for Checklist 
        - CSV-YAML converter to convert YAML into CSV
    - Consolidated different research paper
    - Engineered the prompt for checklist
- Simon Comment
- [ ] Should allow users to add/edit the checklist for their own user. 
- [ ] CSV should be the place to make the editing as it is easily editable. YAML is prepared for the application to consume
- [ ] Google Sheet allows collaboration. Invite Tiffany/Simon to edit. (Refer to Yingzi sheet for Simon comment https://docs.google.com/spreadsheets/d/16mo6pp76_-msJt93iRhHHv24fQKNzVbENQJXdP-7wrQ/edit#gid=313107907)
- [ ] Consolidate the multiple copies into a single source for the checklist. Preferably in CSV
- [ ]

**Comment by tonyshumlh** [comment]
Possible Issue for Checklist:

- Convenience vs Version Control

Possible Issue for the Application:

- Error handling on the variation of LLM response (e.g. some JSON might not be easily parsed)
- Error handling on the truncation of LLM response (e.g. LLM might miss to output the evaluation test of part of the checklist items)

**Comment by tonyshumlh** [comment]
Partner Meeting - 2024/05/17 Week 3
- Comment
- If a leader/teacher evaluates, they might not know the path of test function/file. Better if the report provides the path and line number for easier review -> extract line number with scripts
- Need more information for partial/non-satisfied checklist items, e.g. add function name and line number per each test file
- (Good to Have) output HTML report for more detailed report than report in CLI -> refer to DSCI522 pytest coverage session
- Need error handling when there is no test file / function, e.g. identify edge case, raise error, give 0 scores and give the checklist in human readable format
- Use Regression to evaluate if a parameter (X) is associated with consistency - completeness score (Y)
- For consistency, We can do 1) prompt engineering on checklist, 2) show the explanation and/or uncertainty
- We can come back to Consistency after functionality development and prompt engineering
- Depth vs Breadth on the system: 1) If checklist-oriented, focus on 1 or a few repo and revise and enrich the checklist; 2) focus on certain test area and apply to multiple repos; focus more on 2) in system dev
- Checklist format: 1) QMD
- For Product 1.0, it is important for user to read the checklist instead of editing it
- [ ] Might need a converter to convert code checklist to human readable checklist (HTML,PDF)
- CSV can be embedded into QMD/HTML file, user can use Pandas to make table
- Open Github Issue for Tiffany to add/review the (3-5) checklist item + Slack message, e.g. review N-th item in the website
- For Checklist Citation, can put "General Knowledge" for common sense items and Tiffany will review it

**Comment by JohnShiuMK** [comment]
**Partner Meeting Minutes - May 17, 2024**

**Attendees:** John, Orix, Tiffany (Partner), Tony, Yingzi

**Key Points Discussed:**
**System for Researcher Persona**
1. Evaluation Report Output:
    - Include the path and line number of related functions for each checklist item
    - Provide more elaboration behind partial/non-satisfied checklist items (from a teacher’s perspective)
    - Render the report (including score, summary, and breakdown) into HTML format
    - Refer to examples from DSCI522 Pytest coverage in HTML format
2. Edge Case Handling:
    - Example 1: If a repository has no test files or functions, the system may output a message like "there are no test cases in this repo."
    - Example 2: Detect and handle cases where the project is not related to Machine Learning

**System Evaluation for Ourselves (System Developer Persona)**
1. "Completeness Score" Consistency Metrics:
    - Examine the Consistency improvement using a regression model (Response: Y = Consistency; Explanatory variable: X = the System Change)
    - Continue working on prompt engineering to minimize uncertainty; and/or,
    - Consider outputting the uncertainty of the Score/Evaluation along with the report and explanation
2. Focused Development:
    - Focus on 3-5 checklist items
    - (First) Build the system in depth based on these items using one repository (lightfm)
    - (Then) Apply the system to 4-5 other repositories.

**Checklist for Leader Persona**
1. Checklist Format and Visualization:
    - Confirmed to use CSV format of the checklist as the single source of truth
    - As a version 1.0 of the System, we will focus on users reading the checklist instead of editing it
    - Convert the checklist CSV(s) into a human-readable HTML format using Pandoc or Quarto to facilitate visualization
2. Checklist Collaboration:
    - Use Github issues + Slack for communication with Tiffany
    - Focus each communication on 3-5 checklist items or one area of items instead of the entire checklist
    - For checklist citation, use "General Knowledge" for common sense items. Tiffany will review these citations
